<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
       
        <meta charset="utf-8">
       
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
   
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))           
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
                ; ?>

    
   <script>document.write('<base href="' + document.location + '" />');</script> 
        
   <script src="https://unpkg.com/core-js/client/shim.min.js"></script>

   <script src="https://unpkg.com/zone.js@0.8.4?main=browser"></script>
        <!-- Angular and RxJS umd scripts -->
   <script src="https://unpkg.com/rxjs@5.0.1/bundles/Rx.js"></script>
   <script src="https://unpkg.com/@angular/core/bundles/core.umd.js"></script>
   <script src="https://unpkg.com/@angular/common/bundles/common.umd.js"></script>
   <script src="https://unpkg.com/@angular/compiler/bundles/compiler.umd.js"></script>
   <script src="https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js"></script>
   <script src="https://unpkg.com/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"></script>    
   <script src="/app/app.component.js"></script>
   <script src="/app/app.module.js"></script>
   <script src="/main.js"></script>
 

    </head>
    
    <body>
        
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    
                  <?php echo $this->navigation('navigation')
                             ->menu()
                             ->setUlClass('nav navbar-nav')
                          
                          ;?>
                    
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        <div class="container">
           <!-- Angular 2 render our views-->
           
            <?php echo $this->content;?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        
    </body>
    
    
    
</html>
