
<table class="table">
 <tr>
 <th>Subject</th>
 <th>From</th>
 <th>To</th>
 </tr>
 
            
 <?php foreach ($this->messages as $messageNum=>$message) : ?>
 <tr>
 <td><?php echo $this->escapeHtml($message->subject);?></td>
 <td><?php echo $this->escapeHtml($message->from);?></td>
 <td><?php echo $this->escapeHtml($message->to);?></td>
 <td>
     
     
     
   
 <a class="btn btn-primary" data-toggle="collapse" data-folder='<?php echo $this->messages->getCurrentFolder();?>' data-target="#collapseExample" 
 data-message="<?php echo $messageNum ;?>" id="mail">Read</a>
   
    
        
 </td>
 </tr>
 
 <?php endforeach; ?>
 
  
 </table>



<!-- here result of ajax call -->

<div class="collapse" id="collapseExample">
  <div class="well">
 
  </div>
</div>



<script type="text/javascript">    

        
$(document).on('click.bs.collapse.data-api','[data-toggle=collapse]',function(e){
    
 var $this= $(this);
 var target=$this.attr('data-target');
 var message=$this.attr('data-message');
 var folder=$this.attr('data-folder');  
 var route= $this.attr('data-route'); 
 var collapse=$(target);
 var dom=collapse.find('.well'); 
 
 
 
$.ajax({  
type:'POST',  
url:'/mail/read',
dataType :'json',   
async:true, 
data:{folder:folder,
message:message
},

 
success:function(data){
  
dom.text(data.result);
    
  }
   
});
 
});    
   
   
  
</script>


