<?php

 $title = 'My files';
 $this->headTitle($title);?>

 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <p>
 <a href="<?php echo $this->url('filemenager/default', array('action'=>'upload'));?>">Upload new File</a>
 
 </p>

 <table class="table">
 <tr>
  
 <th>Name</th>
 <th>Index</th> 
 
 </tr>
 <?php foreach ($result as $key=>$value) : ?>
 <tr>
        
 <td><?php echo $this->escapeHtml($value);?></td>
 <td><?php echo $this->escapeHtml($key);?></td>
 <td>
     
 <a href="<?php echo $this->url('filemenager/default',array('action'=>'download','id'=>$key));?>">Download</a>
 
 </td>
 </tr>
 <?php endforeach; ?>
 </table>