<php

 $title = 'My upload';
 $this->headTitle($title);?>

<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php $form->prepare();
 echo $this->form()->openTag($form);?>

<div class="form-element">
    
  <?php $fileElement = $form->get('image-file');  
    echo $this->formLabel($fileElement); 
    echo $this->formFile($fileElement);
    echo $this->formElementErrors($fileElement);?>
    
    
</div>

<button>Submit</button>
<?php echo $this->form()->closeTag(); ?>